# Generated by Django 3.1.6 on 2021-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='places',
            name='place_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
