# Generated by Django 3.1.6 on 2021-02-23 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0002_auto_20210223_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='mobiles_number',
            new_name='mobile_number',
        ),
    ]
